### ISSUE TITLE
Not working with Docker per example

### ISSUE THREAD

**Issue by codebling** [ruoshan/autoportforward#7]
Running this per the documentation does not seem to work. 

```
$ apf redis          

*  ==> : Forwarding local listening ports to (==>) remote ports
*  <== : Forwarding to local ports from (<==) remote listening ports (use -r option)

```

No ports are opened. 

I have tried builds from commit 38558a1 and b8059ea. I've tried the `-d` option, but the log file is empty

Docker version 20.10.12, build e91ed5707e
Linux archlinux 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux

Let me know if you need any other information

**Comment by ruoshan** [comment]
can you log into the container (docker -it exec redis bash) and run some commands while apf is running with `-d`?

```
# in the container
ps aux
cat /tmp/autoportforward.log
```

I don't have an Archlinux. but it does work on my CentOS vm and Mac.

**Comment by codebling** [comment]
Thanks for the quick response. 

There is no `ps` available in the redis image (621ceef7494a), and no files in /tmp in the container. Another image had `ps`, but running it showed only the original process, the `sh` I was using, and `ps` itself (and again no files in `/tmp`).

I tried with a few other images and I got this error about half the time
```
2022/01/05 11:46:24 [ERR] yamux: Invalid protocol version: 79
```

Let me know what else I should try

**Comment by ruoshan** [comment]
Interesting. the way apf works is apf will copy a small agent binary to the container, and that binary will use its stdio to multiplex tcp streams. I am suspecting the binary can't be executed in your containers，maybe because the kernel or the libc loader or the arch doesn't match.

Those errors you got, and with no log file in the container might be caused by that binary failing to run. The next step to assist me debugging would be:
- run an ubuntu container or others that has ps/busybox installed
- run apf -d 
- in other terminal window, log in the container, check if there's a /apf-agent file in the / dir
- if so, see if you can manually run it. let me known if it runs, prints some garbage characters and exits.

Thanks!

**Comment by codebling** [comment]
aha! 
```
./apf-agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./apf-agent)
```

**Comment by ruoshan** [comment]
@codebling mind help me checking if the latest main works? before I tag a new release.

**Comment by codebling** [comment]
works!

**Comment by ruoshan** [comment]
Thank you for your help!

**Comment by codebling** [comment]
Does not exit after forwarding ports, however

**Comment by ruoshan** [comment]
apf should stay running so it can keep the listeners alive. if you close it, forwarding stops.

**Comment by codebling** [comment]
Confirmed. I was expecting the port to show up as forwarded under Docker after running apf but it makes sense that it doesn't. Definitely forwards the port, and forwarding stops when the program is closed. Works great! Thanks for the quick fix! 

By the way, I've made autoportforward available as a [package on arch](https://aur.archlinux.org/packages/autoportforward-git/). It's just in the user repository and builds from the main branch, for now. 

Great idea thanks for the great creation!
